markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "NetCafe"

author: "Joe"
atom-baseurl: "http://hijoe.net"
disqus: "hijosh"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://photo.hijoe.net/folder/josh
  - title: Read+
    class: fa fa-list-ul
    href:  http://dwz.cn/netcafe
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

